import uuid
from typing import Dict, Any, Optional
from app.database import get_supabase
from app.models import User

class AgnoAgent:
    """
    AI agent for code tasks, project assistance, and sandbox integration.
    """
    
    def __init__(self, user: User):
        self.user = user
        self.supabase = get_supabase()

    async def generate_code(self, project_id: str, description: str, agent_type: str, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Generate code based on project context and description.
        Returns dict with:
        {
            "files": {"path/to/file.js": "code content"},
            "reasoning": "explanation of decisions"
        }
        """
        # demo purpose
        files = {
            "components/AIButton.js": f"// Auto-generated by {agent_type} agent\n// {description}\nconsole.log('Hello AI');"
        }
        reasoning = f"Generated {len(files)} files based on description: {description}"

        # Save code changes in database
        for path, content in files.items():
            change_id = str(uuid.uuid4())
            diff = "\n".join([f"+ {line}" for line in content.split("\n")])
            self.supabase.table("code_changes").insert({
                "id": change_id,
                "task_id": str(uuid.uuid4()),  # generate new task if needed
                "file_path": path,
                "change_type": "create",
                "diff": diff,
                "agent_type": agent_type,
                "reasoning": reasoning,
                "approved": None,
            }).execute()

        return {"files": files, "reasoning": reasoning}

    async def apply_change_to_sandbox(self, project_id: str, file_path: str, content: str):
        """
        Apply a generated code change to the E2B sandbox.
        """
        from app.services.sandbox_service import sandbox_service
        sandbox = await sandbox_service.get_sandbox(project_id)
        if not sandbox:
            sandbox = await sandbox_service.create_sandbox(project_id)

        # Traverse nested structure to create/update file
        parts = file_path.split("/")
        node = sandbox
        for part in parts[:-1]:
            if part not in node:
                node[part] = {"type": "directory", "children": {}}
            node = node[part]["children"]

        node[parts[-1]] = {"type": "file", "content": content}
        await sandbox_service.update_sandbox(project_id, sandbox)
